#!/usr/bin/env bash

v=${1%:*}; p=${1#*:}  # split vid:pid into 2 vars
v=${v#${v%%[!0]*}}; p=${p#${p%%[!0]*}}  # strip leading zeros
grep -il "^PRODUCT=$v/$p" /sys/bus/usb/devices/*:*/uevent |
sed s,uevent,, |
xargs -r grep -r '^DEVNAME=' --include uevent | sed -n -e 's/^.*DEVNAME=//p'