# following is the same for PCB version 16 and 21
BATTERY_PCB_BAUD_RATE = 9600

BATTERY_PCB_READY_VID = "04d8"
BATTERY_PCB_READY_PID = "ecb7"

BATTERY_PCB_BOOT_VID = "16d0"
BATTERY_PCB_BOOT_PID = "0557"
